apiVersion: apps/v1
kind: Deployment
metadata:
  name: petshop
spec:
  selector:
    matchLabels:
      app: petshop
  replicas: 1 
  template: 
    metadata:
      labels:
        app: petshop
    spec:
      containers:
      - name: petshop
        image: vaibhavkarade/petshop:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: petshop
spec:
  type: LoadBalancer
  selector:
    app: petshop
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer 
